### ISSUE TITLE
关于pts_bbox_head权重init的疑惑

### ISSUE THREAD

**Issue by heatMa** [ADLab3Ds/TiG-BEV#6]
训练lidar only的时候，`pts_bbox_head`是lidar的head; 

用lidar蒸馏camera时，camere detector的head复用了`pts_bbox_head`（如下面3张图所示）。所以使用lidar的pth初始化参数时，`pts_bbox_head`也被初始化了。

请问这是设计初衷吗？论文中BEV蒸馏部分只说了用lidar的feature去蒸馏camera feature，那camera head的参数应该从头开始训练吧。
![image](https://user-images.githubusercontent.com/18495380/235119121-550364df-4e65-4e2c-8d6b-0aad70d9abc9.png)

![image](https://user-images.githubusercontent.com/18495380/235117029-18c2ce1a-251f-46f3-9b41-ba69c16d73b9.png)
![image](https://user-images.githubusercontent.com/18495380/235117124-ab306b06-ae24-445f-9b8a-5ac9263010b3.png)

**Comment by Lambert-hpx** [comment]
Hello! Thank you for your attention to our work! We didn't use the weights of pts_bbox_head  from our lidar model, because the input channel of the camera model is 256 which is different from the lidar model's (512), then it would not use the incompatible weight. But when you want to align channels, you do have to pay attention to this problem. Thank you for your careful advice on the details of the code.

**Comment by crisz94** [comment]
> Hello! Thank you for your attention to our work! We didn't use the weights of pts_bbox_head from our lidar model, because the input channel of the camera model is 256 which is different from the lidar model's (512), then it would not use the incompatible weight. But when you want to align channels, you do have to pay attention to this problem. Thank you for your careful advice on the details of the code.

@Lambert-hpx 您好，用lidar蒸馏camera时，我的理解是需要在初始化时加载pretrained lidar model，并且把lidar model设置为eval模式，但我在code中没有找到load pertrained lidar model的痕迹，请问是我上面的理解有误吗？
